spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendar_db
    username: calendar_user
    password: Pablojg.25
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true